### PR TITLE
Update scn_Latn.textproto sample text

### PR DESCRIPTION
**Pull request by nathan-williams**
Fix Sicilian language Fonts examples, which are currently not in Sicilian language, but rather likely Corsican or Calabrian. Providing sample found on Wiktionary (http://screen/AyJ5SJLcvAukRjn), which applies the https://cademiasiciliana.org/ standard orthography.

Courtesies of Gino Miceli.

### CODE REVIEW

**Comment by moyogo** [comment]
Looking at the [orthography normalization document] (https://cademiasiciliana.org/wp-content/uploads/2017/10/Proposta-di-normalizzazione-ortografica-comune-della-lingua-siciliana-I-edizione-2017.pdf), the Cademia siciliana uses ḍḍ and ç, and uses à â è ê í î ò ô ú û instead of just à â è ì ò ù. Note that the orthography uses the grave on open vowels a e o and acute on closed vowels i u.

Maybe longer text could be taken from https://unesdoc.unesco.org/ark:/48223/pf0000265904_scn with a "note" or "source" naming the source. It looks like the authors used ì ù instead of í ú, so there may be issues. Either way ì ù should be in the auxiliary exemplar set. Otherwise https://scn.wikipedia.org/wiki/Terra_(pianeta) may be adequate.

It would be nice to have ḍḍ which is quite specific to Sicilian in Europe besides Estonian Swedish.

I can open a separate PR afterwards for these changes if it's easier.

**Comment by giancarloantonucci** [comment]
The document is outdated, and ç, í, ú are no longer in use. Cademia's current standard includes only ḍḍ à â è ê ì î ò ô ù û.

Any text from the translations of the UNESCO Courier (2018 4, 2019 1, 2019 2) will suffice, as long as it adheres to the specified diacritics.

**Comment by gino-m** [comment]
Hi! Happy to consult with the folks at Cademia and reopen this PR with the correct values. Thanks Nathan for kicking this off on the proper channel!

**Comment by giancarloantonucci** [comment]
@gino-m feel free to ask in Cademia's chat. I had the same question two years ago, and you can probably find that conversation in the chat history. The short answer is that we don't distinguish between grave and acute accents because all Sicilian vowels are naturally open. Also ç is outdated and discouraged, with c being the preferred substitute.

**Comment by gino-m** [comment]
Thanks @giancarloantonucci, @moyogo. I'll push a new commit with my edits once I get write access.

**Comment by gino-m** [comment]
@nathan-williams does this look ok the merge?

**Pull request merged**
