### PR TITLE
Arabic and Pashto improvements

### PR DESCRIPTION
**Pull request by yanone**

### CODE REVIEW

**Comment by moyogo** [comment]
Shouldn't the marks be in `marks` instead of `base`?

**Comment by yanone** [comment]
@moyogo I just sorted all non-spacing marks of all languages into the marks category. Thank you for the tip.

**Comment by yanone** [comment]
@moyogo Update: I found a few mistakes in the last step. I'll just roll this one back entirely and only focus on the Arabic in this PR

**Comment by moyogo** [comment]
@yanone you can rebase and remove the undesirable commit instead of having both a commit and its revert commit in the same PR, alternatively you can squash your PR into a single commit.

**Comment by yanone** [comment]
Sorry for the chaos. I'll consider this for the future. I went ahead with it earlier because I wanted to wrap this up before work ends for this year.

**Pull request merged**
