### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by simoncozens**
并决/並决 in https://www.ohchr.org/en/human-rights/universal-declaration/translations/chinese

### CODE REVIEW

**Comment by simoncozens** [comment]
(Noticed by @NightFurySL2001 in https://github.com/google/fonts/pull/8170)

**Comment by NightFurySL2001** [comment]
Thank you. Note for Hant should be 決with 3 dots on the left, not 2 dots for Hans in the comment.

**Comment by simoncozens** [comment]
Oh good point. Anyway the code is correct.

**Comment by NightFurySL2001** [comment]
When can this be reflected to Google Fonts? Still showing the wrong preview there.
image

Additionally, the version on Google Fonts include random spaces after the comma as underlined in the picture above.

**Comment by simoncozens** [comment]
It will be reflected to Google Fonts when the font is next updated.

**Pull request merged**
