### PR TITLE
Sample Texts for mro_Mroo, hoc_Wara, oui_Uygh, skr_Mult,peo_Xpeo, gon_Gonm, ban_Bali

### PR DESCRIPTION
**Pull request by SKing-2003**
Mru, Mro | Source Text: 'Sample Text' in https://www.unicode.org/L2/L2011/11122-n4010-mro-danda.pdf
Ho, Warang Citi | Source Text: Fig 6 (p. 13) inhttps://www.unicode.org/L2/L2012/12118-n4259-warang-citi.pdf
Old Uyghur | Source Text: https://www.babelstone.co.uk/Fonts/OU_Test_B.html
Saraiki, Multani | Source Text: Fig 3 (p. 12) in https://www.unicode.org/L2/L2012/12316-multani.pdf
Old Persian, Old Persian Cuneiform | Source Text: XPa lines 6-11, https://www.livius.org/sources/content/achaemenid-royal-inscriptions/xpa/ and DPa, https://www.livius.org/sources/content/achaemenid-royal-inscriptions/dpa/ (original inscriptions date to the 5th/6th c. BCE)
Gondi, Masaram Gondi | Source Text: Fig 23 (p. 41), http://www.unicode.org/L2/L2015/15090-masaram-gondi.pdf
Balinese | Source Text: Transliteration of text in ban_Latn (UDHR text)

### CODE REVIEW

**Comment by moyogo** [comment]
The Omniglot Mro sample is likely the same as on page 1 of [L2/11-122](https://www.unicode.org/L2/L2011/11122-n4010-mro-danda.pdf). The specimen_16 doesn’t have to repeat speciment_21 twice. The L2/11-122 text is longer and should be used instead.

The Omniglot Mro has some words missing and there’s one typo in the copy here (𖩌𖩓𖩑𖩖𖩗 should be 𖩌𖩓𖩖𖩗, the words 𖩍𖩖𖩌, 𖩅𖩖𖩌 𖩖𖩊 𖩌𖩆𖩓 and 𖩌𖩖𖩁 are missing, the dandas 𖩮‎ and 𖩯 should be used instead of ... or …):
```diff
-    specimen_21: "𖩏𖩖𖩔𖩆𖩊 𖩗𖩖𖩊 𖩎𖩆𖩁 𖩋𖩖 𖩍𖩖𖩌... 𖩏𖩖𖩎𖩊 𖩏𖩖𖩔𖩆𖩊 𖩌𖩖 𖩐𖩓𖩆𖩎 𖩖𖩂𖩑𖩌 𖩎𖩖… 𖩌𖩍𖩖𖩁𖩐𖩖 𖩂𖩑𖩌 𖩎𖩖 𖩖𖩎𖩆𖩁 𖩀𖩑𖩖𖩏 𖩈𖩝𖩐 𖩐𖩖… 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩌𖩓𖩖𖩗 𖩌𖩖 𖩍𖩖𖩁 𖩔𖩓𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩈𖩝𖩆 𖩀𖩐𖩘𖩅 𖩐𖩓𖩆𖩁... \n𖩍𖩖𖩁𖩔𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩗𖩖𖩊 𖩀𖩔𖩆𖩎 𖩈𖩘𖩒 𖩌𖩖 𖩖𖩌𖩆𖩓 𖩎𖩊 𖩌𖩆𖩓 𖩔𖩘 𖩀𖩘𖩌 𖩅𖩖𖩊 𖩆𖩁 𖩊𖩁 𖩌𖩖𖩁 𖩆𖩁𖩊𖩁 𖩈𖩖𖩄𖩖𖩅…"
+    specimen_21: "𖩏𖩖𖩔𖩆𖩊 𖩗𖩖𖩊 𖩍𖩖𖩌 𖩎𖩆𖩁 𖩋𖩖 𖩍𖩖𖩌𖩯 𖩏𖩖𖩎𖩊 𖩏𖩖𖩔𖩆𖩊 𖩌𖩖 𖩐𖩓𖩆𖩎 𖩖𖩂𖩑𖩌 𖩎𖩖𖩯 𖩌𖩍𖩖𖩁𖩐𖩖 𖩂𖩑𖩌 𖩎𖩖 𖩖𖩎𖩆𖩁 𖩀𖩑𖩖𖩏 𖩈𖩝𖩐 𖩐𖩖𖩮 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩌𖩓𖩑𖩖𖩗 𖩌𖩖 𖩍𖩖𖩁 𖩔𖩓𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩈𖩝𖩆 𖩀𖩐𖩘𖩅 𖩐𖩓𖩆𖩁𖩮\n𖩍𖩖𖩁𖩔𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩗𖩖𖩊 𖩀𖩔𖩆𖩎 𖩈𖩘𖩒 𖩌𖩖 𖩖𖩌𖩆𖩓 𖩎𖩊 𖩌𖩆𖩓 𖩅𖩖𖩌 𖩖𖩊 𖩌𖩆𖩓 𖩔𖩘 𖩍𖩖𖩎𖩊 𖩆𖩁 𖩊𖩁 𖩌𖩖𖩁 𖩆𖩁𖩊𖩁 𖩌𖩖𖩁 𖩈𖩖𖩄𖩖𖩅𖩯
```

Omniglot:

L2/11-122:
Screenshot 2023-08-04 at 19 12 52

**Comment by SKing-2003** [comment]
> The Omniglot Mro sample is likely the same as on page 1 of [L2/11-122](https://www.unicode.org/L2/L2011/11122-n4010-mro-danda.pdf). The specimen_16 doesn’t have to repeat speciment_21 twice. The L2/11-122 text is longer and should be used instead.
> 
> The Omniglot Mro has some words missing and there’s one typo in the copy here (𖩌𖩓𖩑𖩖𖩗 should be 𖩌𖩓𖩖𖩗, the words 𖩍𖩖𖩌, 𖩅𖩖𖩌 𖩖𖩊 𖩌𖩆𖩓 and 𖩌𖩖𖩁 are missing, the dandas 𖩮‎ and 𖩯 should be used instead of ... or …):
> 
> ```diff
> -    specimen_21: "𖩏𖩖𖩔𖩆𖩊 𖩗𖩖𖩊 𖩎𖩆𖩁 𖩋𖩖 𖩍𖩖𖩌... 𖩏𖩖𖩎𖩊 𖩏𖩖𖩔𖩆𖩊 𖩌𖩖 𖩐𖩓𖩆𖩎 𖩖𖩂𖩑𖩌 𖩎𖩖… 𖩌𖩍𖩖𖩁𖩐𖩖 𖩂𖩑𖩌 𖩎𖩖 𖩖𖩎𖩆𖩁 𖩀𖩑𖩖𖩏 𖩈𖩝𖩐 𖩐𖩖… 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩌𖩓𖩖𖩗 𖩌𖩖 𖩍𖩖𖩁 𖩔𖩓𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩈𖩝𖩆 𖩀𖩐𖩘𖩅 𖩐𖩓𖩆𖩁... \n𖩍𖩖𖩁𖩔𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩗𖩖𖩊 𖩀𖩔𖩆𖩎 𖩈𖩘𖩒 𖩌𖩖 𖩖𖩌𖩆𖩓 𖩎𖩊 𖩌𖩆𖩓 𖩔𖩘 𖩀𖩘𖩌 𖩅𖩖𖩊 𖩆𖩁 𖩊𖩁 𖩌𖩖𖩁 𖩆𖩁𖩊𖩁 𖩈𖩖𖩄𖩖𖩅…"
> +    specimen_21: "𖩏𖩖𖩔𖩆𖩊 𖩗𖩖𖩊 𖩍𖩖𖩌 𖩎𖩆𖩁 𖩋𖩖 𖩍𖩖𖩌𖩯 𖩏𖩖𖩎𖩊 𖩏𖩖𖩔𖩆𖩊 𖩌𖩖 𖩐𖩓𖩆𖩎 𖩖𖩂𖩑𖩌 𖩎𖩖𖩯 𖩌𖩍𖩖𖩁𖩐𖩖 𖩂𖩑𖩌 𖩎𖩖 𖩖𖩎𖩆𖩁 𖩀𖩑𖩖𖩏 𖩈𖩝𖩐 𖩐𖩖𖩮 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩌𖩓𖩑𖩖𖩗 𖩌𖩖 𖩍𖩖𖩁 𖩔𖩓𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩈𖩝𖩆 𖩀𖩐𖩘𖩅 𖩐𖩓𖩆𖩁𖩮\n𖩍𖩖𖩁𖩔𖩊𖩏 𖩌𖩆𖩎𖩄𖩝𖩓 𖩏𖩖𖩔𖩆𖩊 𖩈𖩝𖩌𖩇𖩆 𖩗𖩖𖩊 𖩀𖩔𖩆𖩎 𖩈𖩘𖩒 𖩌𖩖 𖩖𖩌𖩆𖩓 𖩎𖩊 𖩌𖩆𖩓 𖩅𖩖𖩌 𖩖𖩊 𖩌𖩆𖩓 𖩔𖩘 𖩍𖩖𖩎𖩊 𖩆𖩁 𖩊𖩁 𖩌𖩖𖩁 𖩆𖩁𖩊𖩁 𖩌𖩖𖩁 𖩈𖩖𖩄𖩖𖩅𖩯
> ```
> 
> Omniglot:  [ 68747470733a2f2f7777772e6f6d6e69676c6f742e636f6d2f696d616765732f6c616e6773616d706c65732f736d705f6d726f322e676966 ](https://camo.githubusercontent.com/19602c60c120eace7753817ff4d4bf16a447b5d6d90bfcc53f16d428edb30871/68747470733a2f2f7777772e6f6d6e69676c6f742e636f6d2f696d616765732f6c616e6773616d706c65732f736d705f6d726f322e676966) [ ](https://camo.githubusercontent.com/19602c60c120eace7753817ff4d4bf16a447b5d6d90bfcc53f16d428edb30871/68747470733a2f2f7777772e6f6d6e69676c6f742e636f6d2f696d616765732f6c616e6773616d706c65732f736d705f6d726f322e676966) L2/11-122: Screenshot 2023-08-04 at 19 12 52

Apologies, I only just saw this! Will correct now!

**Comment by SKing-2003** [comment]
@moyogo Many thanks for checking this - I hope I've implemented the changes to Mro correctly! I'm not particularly experienced with any of these scripts so I'm very glad to have a second pair of eyes on them!

**Comment by simoncozens** [comment]
This is great, thank you Ffion! (I shall give you a call on Monday to catch up.)

**Pull request merged**
