### PR TITLE
Fix sample text of Cantonese; Add sample text for Hakka; Rename Chinese languages in a consistent format

### PR DESCRIPTION
**Pull request by laubonghaudoi**
I originally opened https://github.com/google/fonts/pull/7782 but Chris told me to move the PR here. So this PR fixes the following issues:

1. The original sample text of `yue_Hant` (Cantonese) is actually in Simplified Chinese characters. This PR updates them into Traditional Chinese characters.
2. Sample text for Hakka Chinese was missing. This PR adds sample texts for Hakka.
3. The naming of Chinese languages was inconsistent. This PR renames them with the consistent `XX Chinese` format.
4. [Zhuang](https://en.wikipedia.org/wiki/Zhuang_languages) still has an active speaker population and an ongoing revitalizing effort to bring back the writing of using [Sawndip](https://en.wikipedia.org/wiki/Sawndip). This PR sets its population number and removes the `historical: true` tag.

BTW, it seems like the downstream https://github.com/google/fonts is not in sync with this repo. As you can see from that PR, the downstream google/fonts contains `wuu_Hant.textproto`, `cjy_Hant.textproto`, `gan_Hant.textproto`, `hsn_Hant.textproto` and `wuu_Hant.textproto` while this googlefonts/lang is missing those files. I am not sure if this is worth investigating but this PR is adding those files back.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@nathan-williams a proposal for more front end sample text changes

**Comment by davelab6** [comment]
I defer to Simon but overall this LGTM :) Simon is out this week for UK holidays but I expect can review next week :)

**Comment by simoncozens** [comment]
This is excellent, thank you very much!

**Comment by moyogo** [comment]
Why is the new pattern "XYZ Chinese", "XYZ Chinese (Simplified)", "XYZ Chinese (Latin)"?
Why is "Traditional" assumed to be the default? Would having "(Simplified)" make sense for some of them?

Isn’t the "name" supposed to match the ISO 693 name and "preferred_name" the one used by GF?

There are also some inconsistencies:

 code | name | preferred_name | comment
 ---  | ---- | -------------- | -------
cjy_Hans | Jin Chinese (Simplified) |
cjy_Hant | Jin Chinese |      |
gan_Hans | Gan Chinese (Simplified) | Gan Chinese (Simplified) | Redundant preferred_name as is.
gan_Hant | Gan Chinese | Gan Chinese | Redundant preferred_name as is.
hak_Hans | Hakka Chinese (Simplified) |
hak_Hant | Hakka Chinese | | 
hak_Latn | Hakka Chinese (Latin) |
hsn_Hans | Xiang Chinese (Simplified) |
hsn_Hant | Xiang Chinese | | 
lzh_Hans | Literary Chinese (Simplified) | Does it actually make sense to have this one? It doesn’t have data anyway.
lzh_Hant | Literary Chinese | | 
lzh_Phag | Literary Chinese, Phags-pa | "Literary Chinese (Phags-pa)"
nan_Hans | Southern Min Chinese (Simplified) |
nan_Hant | Southern Min Chinese | |
nan_Latn | Southern Min Chinese (Latin) |
wuu_Hans | Wu Chinese (Simplified) | Shanghainese (Simplified)
wuu_Hant | Wu Chinese | Shanghainese | 
yue_Hani | Yue Chinese | Cantonese | Data is pretty much a copy of "yue_Hant". Hani is a superset of Hant and Hans. Should it be removed?
yue_Hans | Yue Chinese (Simplified) | Cantonese (Simplified)
yue_Hant | Yue Chinese | Cantonese | 
za_Hans | Zhuang, Simplified Han | | Does it actually make sense to have this one? It doesn’t have data anyway.
za_Hant | Zhuang, Traditional Han | | "Zhuang (Sawndip)"?
za_Latn | Zhuang | | "Zhuang (Latin)"?
zh_Hans | Simplified Chinese | | "Chinese (Simplified)"?
zh_Hant | Chinese (Traditional) |
zh_Hebr | Chinese, Hebrew | | "Chinese (Hebrew)"?
zh_Phag | Chinese, Phags-pa | | "Chinese (Phags-pa)"?

There are plenty of other multipscript languages with "<language name>, <script name>" instead "<language name> (<script name>)" like "Pular" and "Pular, Adlam" or "Mandar" and "Mandar, Buginese". Should these be normalized to use parentheses as well?

**Comment by laubonghaudoi** [comment]
@moyogo  You are right that some of the preferred names are redundant. They there simply because they were originally there for unknown reasons. I want to minimize the changes and risks so I didn't delete them. If you believe they are safe to delete we can make another PR. I have the same confusions about the Simplified Literary Chinese and Simplified Zhuang as well. Again I didn't touch them because they were there in the beginning for unknown reasons. We might need to find the original authors of them and ask for the rationales of adding them.

**Comment by moyogo** [comment]
> So making Traditional as the default would keep the naming consistency.

Weren't "Simplified" and "Traditional" consistently present before? 

The mixed up samples come from https://github.com/eric-muller/udhr/ they should also be fixed there if possible.

**Comment by laubonghaudoi** [comment]
The original naming pattern was inconsistent. It had `Chinese Jinyu` in hans, `Chinese Yue` in hani and `Wu Chinese` with an autonym (I don't know what autonym does here). And as you said Literary Chinese in Simplified and Zhuang in Simplified wouldn't make sense. They are written in only one script which is the traditional one. That's reason why I assume the traditional script as the default. Otherwise creating `Literary Chinese (Traditional)` would be quite confusing, because there is simply no non-traditional Literary Chinese.

**Pull request merged**
