### PR TITLE
doi_Dogr, hi_Mahj, sat_Olck, sd_Khoj, sd_Khud, sd_Sind

### PR DESCRIPTION
**Pull request by SKing-2003**

### CODE REVIEW

**Comment by RosaWagner** [comment]
Thanks @SKing-2003 for your PR.

This PR modifies doi_Dogr, hi_Mahj, sat_Olck, sd_Khoj and sd_Khud 
and remove sd_Sind

**Comment by simoncozens** [comment]
Ffion (@SKing-2003): thanks for this first batch. I'm going to review and add some comments for you for future reference, but I'll address them in your repo and update this pull request. I suggest that we get these fixed up and then merged first before you work on the next batch of samples.

For reference, these new sample texts up to this point are all UDHR transliterations:

* doi_Dogr text is from UDHR Dogri translation at https://en.wikipedia.org/wiki/Dogri_language 
* hi_Mahj is a transliteration of the UDHR text from hi_Deva
* sat_Olck is a transliteration of the UDHR text from sat_Deva
* sd_Khoj and sd_Khud are transliterations of UHDR from sd_Arab

**Comment by SKing-2003** [comment]
Thanks Simon - Hopefully I've corrected these errors now, though if I've missed please flag them up.

-Ffion

**Comment by simoncozens** [comment]
Nice, thank you. These are all UDHR, so we can happily merge these.

**Pull request merged**
