### PR TITLE
Delete arabic control characters mark-ar (0x061C) and lefttorightmark (0x200E)

### PR DESCRIPTION
**Pull request by yanone**
These are invisible control characters and are confusing when part of glyphsets.

I used search-and-replace, so the files should be good despite the characters being invisible.

### CODE REVIEW

**Comment by yanone** [comment]
Could you please publish a package update after merging this? Thank you.

**Comment by moyogo** [comment]
I think this can be merged. However, knowing these characters are used can still be useful at other level of language support so it would be good to have other opinions.

**Comment by yanone** [comment]
That's an interesting point. If they shall stay in the language DB, I could instead maybe filter for invisible control characters when assembling the glyphsets, leaving the languages untouched here.

**Comment by yanone** [comment]
I just implemented a filter for `Cc` and `Cf` Unicode category characters in `glyphsets` and it removes exactly those two plus a third `righttoleftmark` in Arabic Plus that I didn’t catch earlier.

Personally I’m happy with this and will let you decide whether to close the PR or not.

**Comment by simoncozens** [comment]
I think control characters don't belong in these lists.

**Pull request merged**
